name: Test Markdown Body
description: Testing markdown item in body
body:
  - type: markdown
    attributes:
      value: |
        some markdown
  - type: textarea
    id: x
    attributes:
      label: hello
